# Generated by Django 4.1.6 on 2023-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='user_name', max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Mode',
                'db_table': 'test_mode',
                'ordering': ('created_at',),
                'permissions': (('can_read', 'Can read'),),
                'get_latest_by': 'created_at',
                'unique_together': {('name', 'description')},
            },
        ),
    ]
