# Generated by Django 4.1.6 on 2023-10-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_author_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
