# Generated by Django 4.1.6 on 2023-05-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_country_state_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population_factor',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='state',
            name='population_factor',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
