# Generated by Django 5.0 on 2024-01-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_author_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_name", models.CharField(max_length=50)),
                (
                    "product_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("product_quantity", models.IntegerField()),
                (
                    "expected_earning",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "actual_earning",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
