# Generated by Django 5.0 on 2024-01-13 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_report"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
