# Generated by Django 5.0 on 2024-01-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_delete_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.PositiveSmallIntegerField()),
                ("city", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "db_table": "student",
            },
        ),
    ]
